name: "Monokle Validation"
description: "Validate your Kubernetes resources."
runs:
  using: "node16"
  main: "dist/index.js"
inputs:
  path:
    description: "Relative path to a directory or a YAML file with Kubernetes resources."
    default: "bundle.yaml"
  config:
    description: "Relative path to the Monokle validation configuration file."
    default: "monokle.validation.yaml"
outputs:
  sarif:
    description: "Relative path to a SARIF file which contains the validation response."
